# config.yaml

# Project root; current working dir
projPath: "/path/to/CUTTAGpipeline"
fastq_dir: "/path/to/CUTTAGpipeline/fastq/" # where fastq files are

# Bowtie2 indices (already built)
BOWTIE_INDEX: '/path/to/bowtie2Index/hg38'
SPIKEIN_INDEX: '/path/to/bowtie2Index/Ecoli'
chromSize: "/path/to/hg38.chrom.sizes"

picard_cmd: "java -jar $EBROOTPICARD/picard.jar"
seacr_script: "/path/to/CUTTAGpipeline/SEACR/SEACR_1.3.sh"
histControl: "IgG_rep1"

threads:
  fastqc: 2
  bowtie2: 8
  samtools: 4

# Output directory for FastQC reports
fastqc_outdir: "fastqFileQC"

# Output directory for Alignment
alignment_dir: "alignment"